# Generated by Django 3.0.3 on 2020-05-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='issedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.students'),
        ),
    ]
