# Generated by Django 3.0.3 on 2020-05-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200509_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='fine',
        ),
    ]
